name: PR Comment for Auto Merge

on:
  issue_comment:
    branches:
      - 'release/*'
    paths-ignore:
      - '.github/**'

jobs:
  pr_commented:
    name: PR comment
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'auto_merge' }}
    runs-on: ubuntu-latest
    steps:
      - id: 'get-branch'
        run: |
          echo ::set-output name=branch::$(gh pr view $PR_NO --repo $REPO --json headRefName --jq '.headRefName')
          echo ::set-output name=target-branch::$(gh repo view --json defaultBranchRef --jq .defaultBranchRef.name)
        env:
          REPO: ${{ github.repository }}
          PR_NO: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.BAAS_BOT_PAT }}

      - name: Checkout
        run : echo ${{ steps.get-branch.outputs.branch }} - ${{ steps.get-branch.outputs.target-branch }}
