name: PR Comment for Auto Merge

on:
  issue_comment:
    branches:
      - 'release/*'
    paths-ignore:
      - '.github/**'

jobs:
  pr_commented:
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Check Comment for Action
        if: github.event.comment.body == 'auto_merge'
        uses: devmasx/merge-branch@master
        with:
          type: now
          head_to_merge: ${{ github.ref }}
          target_branch: main
          github_token: ${{ secrets.BAAS_BOT_PAT }}
