name: All Plans Complete on Comment

on:
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '.github/**'

jobs:
  pr_all_plans_complete:
    name: Auto Merge Comment
    runs-on: ubuntu-latest
    steps:
      - name: "all_plans_complete"
        run: exit 1   
