name: PR Comment for Auto Merge

on:
  issue_comment:
    branches:
      - 'release/*'
    paths-ignore:
      - '.github/**'

jobs:
  pr_commented:
    name: PR comment
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'auto_merge' }}
    runs-on: ubuntu-latest
    steps:
      - name: Get source branch
        id: get-branch
        run: echo ::set-output name=branch::$(gh pr view $PR_NO --repo $REPO --json headRefName --jq '.headRefName')
        env:
          REPO: ${{ github.repository }}
          PR_NO: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.BAAS_BOT_PAT }}
      - name: Merge PR
        uses: plm9606/automerge_actions@1.2.2
        with:
          # The label name to automatically merge. Default is "automerge".
          label-name: ''
          # The number of reviewers to automatically merge. Default is 1.
          reviewers-number:
          # The merge method ("merge", "squash", "rebase"). Default is "merge"
          merge-method:
          # Let the bot delete the merged branch. true or false.
          auto-delete:
          # GitHub WebHook Secret Token
          github-token: ${{ secrets.GITHUB_TOKEN }}
