name: PR Comment for Auto Merge

on:
  issue_comment:
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  pr_commented:
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Check Comment for Action
        if: github.event.comment.body == 'auto_merge'
        run: echo "Deploying to production server on branch ${{ github.event.pull_request.head.ref }}"
        