name: PR Comment for All Plans Complete

on:
  issue_comment:
    types:
      - created
    branches:
      - 'main'
    paths-ignore:
      - '.github/**'

jobs:
  pr_commented:
    name: Auto Merge Comment
    if: github.event.issue.pull_request && github.event.comment.body == 'all_plans_complete'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - name: "all_plans_complete"
        run: echo A comment on issue ${{ github.event.issue.number }}   
