name: PR Comment for Auto Merge

on:
  issue_comment:
    branches:
      - 'release/*'
    paths-ignore:
      - '.github/**'

jobs:
  pr_commented:
    name: PR comment
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'auto_merge' }}
    runs-on: ubuntu-latest
    steps:
      - name: Get source branch
        id: get-branch
        run: echo ::set-output name=branch::$(gh pr view $PR_NO --repo $REPO --json headRefName --jq '.headRefName')
        env:
          REPO: ${{ github.repository }}
          PR_NO: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Merge PR
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: ${{ steps.get-branch.outputs.branch }}
          target_branch: ${{ github.event.repository.default_branch }}
          github_token: ${{ github.BAAS_BOT_PAT }}
          
