name: PR Comment for Auto Merge

on:
  issue_comment:
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  pr_commented:
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Check Comment for Action
        if: github.event.comment.body == 'auto_merge'
        uses: 'davideviolante/pr-automerge-action@v1.2.2'
        env:
          GITHUB_TOKEN: ${{ secrets.BAAS_BOT_PAT }}
        with:
          merge-method: 'squash' # Default 'squash'
          min-approvals: 0 # Default 2
          base-ref: 'test-comment-1' # Default 'dev'          
