name: PR Comment for Auto Merge

on:
  issue_comment:
    branches:
      - 'release/*'
    paths-ignore:
      - '.github/**'

jobs:
  pr_commented:
    name: PR comment
    if: ${{ github.event.issue.pull_request && github.event.comment.body == 'auto_merge' }}
    runs-on: ubuntu-latest
    steps:
      - name: Get source branch
        id: get-branch
        run: echo ::set-output name=branch::$(gh pr view $PR_NO --repo $REPO --json headRefName --jq '.headRefName')
        env:
          REPO: ${{ github.repository }}
          PR_NO: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.BAAS_BOT_PAT }}
      - name: Merge PR
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ secrets.BAAS_BOT_PAT }}
          source: ${{ steps.get-branch.outputs.branch }}
          target: ${{ github.event.repository.default_branch }}
          webhook_url: #if present add the Slack webhook
          
