name: PR Comment for Auto Merge

on:
  issue_comment:
    branches:
      - 'release/*'
    paths-ignore:
      - '.github/**'

jobs:
  pr_commented:
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: resolve pr refs
       id: refs
       uses: eficode/resolve-pr-refs@main
       with:
         token: ${{ secrets.BAAS_BOT_PAT }}

