name: Update All Plans Complete on Comment

on:
  issue_comment:
    types:
      - created
    branches:
      - 'main'
    paths-ignore:
      - '.github/**'

jobs:
  pr_commented:
    name: Update All Plans Complete
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'update_all_plans_complete')
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - name: Get sha
        id: getsha
        run: |
          echo ${{ github.event.pull_request.head.sha }}
          echo "::set-output name=head_sha::$(gh api /repos/{owner}/{repo}/pulls/${{ github.event.inputs.pr }} |jq -r '.head.sha')"      
      - name: update_all_plans_complete
        shell: bash
        run: |
          if [ "${{ github.event.review.state }}" == 'approved' ]
          then
            gh api "/repos/{owner}/{repo}/statuses/${{ steps.getsha.outputs.head_sha }}" \
              -f context="all_plans_complete" \
              -f description="All are successful" \
              -f state="success"
          else
            echo "The PR must be approved first !!"
            gh api "/repos/{owner}/{repo}/statuses/393e0dae8576ce7a6f0229440b40e82960dd55b6" \
              -f context="Auto Merge Comment" \
              -f description="All are successful" \
              -f state="success"
            exit 1
          fi
